name: Java CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build jar
        run: ./mvnw package -DskipTests

      - name: Set up Docker Auth for GCR
        run: echo "${{ secrets.GCP_SA_KEY }}" | base64 -d > key.json

      - run: |
          gcloud auth activate-service-account --key-file=key.json
          gcloud auth configure-docker

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/YOUR_PROJECT_ID/java-app:${{ github.sha }} .
          docker push gcr.io/YOUR_PROJECT_ID/java-app:${{ github.sha }}

      - name: Update image tag in GitOps repo
        run: |
          git clone https://x-access-token:${{ secrets.GITOPS_TOKEN }}@github.com/YOU/gitops-repo.git
          cd gitops-repo/apps/java-app
          sed -i "s|image: .*|image: gcr.io/YOUR_PROJECT_ID/java-app:${{ github.sha }}|" deployment.yaml
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -am "Update image tag"
          git push
