name: Build and Deploy to GKE via Argo CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: inner-root-456714-i7
  IMAGE_NAME: action-cicd
  GCR_REGION: gcr.io
  GITOPS_REPO: git@github.com:amitsingh977/gitops-config.git
  GITOPS_REPO_DIR: apps/java-app
  DEPLOYMENT_FILE: deployment.yml

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JAR with Maven
        run: mvn clean package

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker ${{ env.GCR_REGION }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=${{ env.GCR_REGION }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Set up SSH agent for GitOps repo
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.GITOPS_DEPLOY_KEY }}

      - name: Clone GitOps repo
        run: git clone ${{ env.GITOPS_REPO }} gitops

      - name: Update deployment manifest with new image
        run: |
          cd gitops/${{ env.GITOPS_REPO_DIR }}
          sed -i "s|image:.*|image: ${{ env.IMAGE_TAG }}|" ${{ env.DEPLOYMENT_FILE }}

      - name: Commit and Push updated manifest to GitOps repo
        run: |
          cd gitops/${{ env.GITOPS_REPO_DIR }}
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin ${{ env.GITOPS_REPO }}
          git add ${{ env.DEPLOYMENT_FILE }}
          git commit -m "Update image to ${{ env.IMAGE_TAG }}" || echo "No changes to commit"
          git push origin main
